dataset: brats
train_dir: /home/..
val_dir: /home/..
batch_size: 2
n_cls: 4
in_dim: 4

net: unet3d
f_dim: 32

optim: sgd
lr: 0.01
weight_decay: 0

loss: ce+dice

epochs: 200
val_step: 1

group_epoch: 2

vd_p:
  - 0.6
  - 0.5

device: cuda:0



